server:
  port: 8080

#server:
#  address: 0.0.0.0
#  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sdi?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
  flyway:
      schemas:
          - sdi


#spring:
#  datasource:
#    url: jdbc:mysql://google/nutrition_app?cloudSqlInstance=mythic-tenure-386918:us-west2:nutrition-app&socketFactory=com.google.cloud.sql.mysql.SocketFactory
#    username: root
#    password: Password123!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  flyway:
#    schemas:
#        - nutrition_app